# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sdm632-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter V430A V420A,$(TARGET_DEVICE)),)

endif
